// SQLite with FTS5, at .vaan/memory/state.db.
//
// Why a native dependency rather than a flat file: ranked retrieval needs real
// BM25 scoring, and Node's built-in node:sqlite ships compiled *without* FTS5
// (nodejs/node#56951), so `CREATE VIRTUAL TABLE … USING fts5` throws there.
// better-sqlite3 bundles its own SQLite with FTS5 enabled. The alternative was
// hand-rolling TF-IDF over JSON files, which we'd then own and get subtly wrong.
//
// Nothing in here is allowed to throw. A corrupt database, a locked file, a
// disk that filled up — none of that should stop the agent answering. Every
// public method falls back to "no memory" and warns once.

import Database from "better-sqlite3";
import { mkdirSync, writeFileSync } from "node:fs";
import { databaseFile, memoryDir, memoryMirror } from "../paths.js";
import {
  EMPTY_RECALL,
  type Fact,
  type Memory,
  type Recall,
  type Remembered,
  type Turn,
} from "./index.js";
import { toMatchQuery } from "./search.js";

const SCHEMA = `
CREATE TABLE IF NOT EXISTS turns (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  scope      TEXT NOT NULL,
  ts         TEXT NOT NULL,
  user_text  TEXT NOT NULL,
  reply_text TEXT NOT NULL,
  tools_json TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS turns_by_scope ON turns(scope, id DESC);

CREATE TABLE IF NOT EXISTS facts (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  scope      TEXT NOT NULL,
  text       TEXT NOT NULL,
  created_at TEXT NOT NULL,
  source     TEXT NOT NULL,
  UNIQUE(scope, text)
);

CREATE VIRTUAL TABLE IF NOT EXISTS turns_fts USING fts5(user_text, reply_text);
`;

/**
 * Confirm this build of SQLite actually has FTS5. Returns the failure message,
 * or undefined when all is well. The postinstall script runs the same check;
 * the onboarding runs it again because a working install can still be moved to
 * a machine whose native module doesn't load.
 */
export function probeFts5(): string | undefined {
  try {
    const db = new Database(":memory:");
    db.exec("CREATE VIRTUAL TABLE probe USING fts5(x)");
    db.close();
    return undefined;
  } catch (err) {
    return err instanceof Error ? err.message : String(err);
  }
}

export interface SqliteOptions {
  /** The workspace. `.vaan/memory` is created inside it. */
  dir: string;
  turnLimit?: number;
  factLimit?: number;
}

export function openMemory(opts: SqliteOptions): Memory {
  const turnLimit = opts.turnLimit ?? 5;
  const factLimit = opts.factLimit ?? 64;

  mkdirSync(memoryDir(opts.dir), { recursive: true });
  const db = new Database(databaseFile(opts.dir));
  db.pragma("journal_mode = WAL");
  db.exec(SCHEMA);

  const statements = {
    facts: db.prepare(
      "SELECT id, text, created_at, source FROM facts WHERE scope = ? ORDER BY id LIMIT ?",
    ),
    insertFact: db.prepare(
      "INSERT OR IGNORE INTO facts (scope, text, created_at, source) VALUES (?, ?, ?, ?)",
    ),
    deleteFact: db.prepare("DELETE FROM facts WHERE scope = ? AND id = ?"),
    insertTurn: db.prepare(
      "INSERT INTO turns (scope, ts, user_text, reply_text, tools_json) VALUES (?, ?, ?, ?, ?)",
    ),
    indexTurn: db.prepare("INSERT INTO turns_fts (rowid, user_text, reply_text) VALUES (?, ?, ?)"),
    recent: db.prepare(
      "SELECT id, ts, user_text, reply_text, tools_json FROM turns WHERE scope = ? ORDER BY id DESC LIMIT ?",
    ),
    search: db.prepare(
      `SELECT t.id, t.ts, t.user_text, t.reply_text, t.tools_json
         FROM turns_fts f JOIN turns t ON t.id = f.rowid
        WHERE turns_fts MATCH ? AND t.scope = ?
        ORDER BY bm25(turns_fts) LIMIT ?`,
    ),
  };

  const readFacts = (scope: string): Fact[] =>
    (statements.facts.all(scope, factLimit) as FactRow[]).map(toFact);

  function mirror(scope: string): void {
    // The database is authoritative. This file is for humans, and is
    // regenerated from the facts table every time they change.
    const facts = readFacts(scope);
    const lines = [
      "# MEMORY.md",
      "",
      "<!-- Generated by Vaan from .vaan/memory/state.db. Edits here are overwritten.",
      "     To remove a fact, use /forget in the REPL. -->",
      "",
      ...(facts.length === 0
        ? ["_Nothing remembered yet._"]
        : facts.map((fact) => `- ${fact.text}  \`#${fact.id}\``)),
      "",
    ];
    writeFileSync(memoryMirror(opts.dir), lines.join("\n"), "utf8");
  }

  return {
    async recall(scope, query): Promise<Recall> {
      return guard(EMPTY_RECALL, () => {
        const facts = readFacts(scope);
        const match = toMatchQuery(query);
        const rows = match
          ? (statements.search.all(match, scope, turnLimit) as TurnRow[])
          : (statements.recent.all(scope, turnLimit) as TurnRow[]);
        return { facts, turns: rows.map(toTurn) };
      });
    },

    async remember(scope, item): Promise<void> {
      return guard(undefined, () => {
        if (item.kind === "fact") {
          const text = item.text.trim();
          if (!text) return;
          statements.insertFact.run(scope, text, new Date().toISOString(), item.source ?? "tool");
          mirror(scope);
          return;
        }
        const result = statements.insertTurn.run(
          scope,
          new Date().toISOString(),
          item.userText,
          item.replyText,
          JSON.stringify(item.tools),
        );
        statements.indexTurn.run(result.lastInsertRowid, item.userText, item.replyText);
      });
    },

    async forget(scope, factId): Promise<number> {
      return guard(0, () => {
        const removed = statements.deleteFact.run(scope, factId).changes;
        if (removed > 0) mirror(scope);
        return removed;
      });
    },

    close() {
      guard(undefined, () => db.close());
    },
  };
}

interface FactRow {
  id: number;
  text: string;
  created_at: string;
  source: string;
}

interface TurnRow {
  id: number;
  ts: string;
  user_text: string;
  reply_text: string;
  tools_json: string;
}

const toFact = (row: FactRow): Fact => ({
  id: row.id,
  text: row.text,
  createdAt: row.created_at,
  source: row.source,
});

const toTurn = (row: TurnRow): Turn => ({
  id: row.id,
  ts: row.ts,
  userText: row.user_text,
  replyText: row.reply_text,
  tools: parseTools(row.tools_json),
});

function parseTools(json: string): string[] {
  try {
    const parsed: unknown = JSON.parse(json);
    return Array.isArray(parsed)
      ? parsed.filter((item): item is string => typeof item === "string")
      : [];
  } catch {
    return [];
  }
}

let warned = false;

/** Run `fn`, and on any failure warn once and hand back `fallback`. */
function guard<T>(fallback: T, fn: () => T): T {
  try {
    return fn();
  } catch (err) {
    if (!warned) {
      warned = true;
      const detail = err instanceof Error ? err.message : String(err);
      process.stderr.write(`vaan: memory is unavailable (${detail}). Continuing without it.\n`);
    }
    return fallback;
  }
}

export { toMatchQuery };
